// tools/solidjs-js-tsdk-template-master031/src/components/Root.jsx
import { ErrorBoundary, Switch, Match } from 'solid-js';

import { App } from '@/components/App.jsx';
import { TonConnectUIProvider } from '@/tonconnect/TonConnectUIProvider.jsx';
import { getWebApp } from '@/utils/getWebApp.js';

/**
 * @returns {import('solid-js').JSXElement}
 */
function Inner() {
  if (getWebApp().initDataUnsafe.start_param === 'debug') {
    import('eruda').then((lib) => lib.default.init());
  }

  return (
    <TonConnectUIProvider
      manifestUrl={new URL('tonconnect-manifest.json', window.location.href).toString()}
    >
      <App/>
    </TonConnectUIProvider>
  );
}

/**
 * @returns {import('solid-js').JSXElement}
 */
export function Root() {
  return (
    <ErrorBoundary
      fallback={err => {
        console.error('ErrorBoundary handled error:', err);

        return (
          <div>
            <p>ErrorBoundary handled error:</p>
            <blockquote>
              <code>
                <Switch fallback={JSON.stringify(err)}>
                  <Match when={typeof err === 'string' ? err : false}>
                    {v => v()}
                  </Match>
                  <Match when={err instanceof Error ? err.message : false}>
                    {v => v()}
                  </Match>
                </Switch>
              </code>
            </blockquote>
          </div>
        );
      }}
    >
      <Inner/>
    </ErrorBoundary>
  );
}

// tools/Next.js TS 020/src/components/Root/Root.jsx
'use client';

import { useEffect, useMemo } from 'react';
import { TonConnectUIProvider } from '@tonconnect/ui-react';
import { AppRoot } from '@telegram-apps/telegram-ui';

import { ErrorBoundary } from '@/components/ErrorBoundary';
import { ErrorPage } from '@/components/ErrorPage';
import { useDidMount } from '@/hooks/useDidMount';
import { getWebApp } from '@/utils/getWebApp';

import './styles.css';

function RootInner({ children }) {
  const debug = getWebApp().initDataUnsafe.start_param === 'debug';
  const manifestUrl = useMemo(() => {
    return new URL('tonconnect-manifest.json', window.location.href).toString();
  }, []);

  // Enable debug mode to see all the methods sent and events received.
  useEffect(() => {
    if (debug) {
      import('eruda').then((lib) => lib.default.init());
    }
  }, [debug]);

  return (
    <TonConnectUIProvider manifestUrl={manifestUrl}>
      <AppRoot
        appearance={getWebApp().colorScheme}
        platform={['macos', 'ios'].includes(getWebApp().platform) ? 'ios' : 'base'}
      >
        {children}
      </AppRoot>
    </TonConnectUIProvider>
  );
}

export function Root(props) {
  // Unfortunately, Telegram Mini Apps does not allow us to use all features of the Server Side
  // Rendering. That's why we are showing loader on the server side.
  const didMount = useDidMount();

  return didMount ? (
    <ErrorBoundary fallback={ErrorPage}>
      <RootInner {...props}/>
    </ErrorBoundary>
  ) : <div className="root__loading">Loading</div>;
}
