// tools/solidjs-js-tsdk-template-master031/src/components/DisplayData/DisplayData.jsx
import { For, Match, Switch } from 'solid-js';

import { RGB } from '@/components/RGB/RGB.jsx';

import './DisplayData.css';

/**
 * @typedef {object} DisplayDataRow
 * @property {string} title
 * @property {string | boolean | import('solid-js').JSXElement} [value]
 */

/**
 * @param {{ rows: DisplayDataRow[] }} props
 * @return {import('solid-js').JSXElement}
 */
export function DisplayData(props) {
  return (
    <div>
      <For each={props.rows}>
        {(row) => (
          <div class="display-data__line">
            <span class="display-data__line-title">{row.title}</span>
            <span class="display-data__line-value">
              <Switch fallback={row.value}>
                <Match
                  when={
                    typeof row.value === 'string' && row.value.match(/^#[a-f0-9]{3,6}$/i)
                      ? row.value
                      : false
                  }
                >
                  {(color) => <RGB color={color()}/>}
                </Match>
                <Match when={row.value === false}>❌</Match>
                <Match when={row.value === true}>✔️</Match>
                <Match when={row.value === undefined}><i>empty</i></Match>
              </Switch>
            </span>
          </div>
        )}
      </For>
    </div>
  );
}

// tools/Next.js TS 020/src/components/DisplayData/DisplayData.jsx
import { Cell, Checkbox, Section } from '@telegram-apps/telegram-ui';

import { RGB } from '@/components/RGB/RGB.jsx';
import { Link } from '@/components/Link/Link.jsx';

import './styles.css';

/**
 * @typedef {object} DisplayDataRow
 * @property {string} title
 * @property {string | boolean | import('react').ReactNode} [value]
 */

/**
 * @param {import('react').ReactNode} header - section header.
 * @param {DisplayDataRow[]} rows - list of rows to be displayed.
 * @return {import('react').JSX.Element}
 */
export function DisplayData({ header, rows }) {
  return (
    <Section header={header}>
      {rows.map((item, idx) => {
        let valueNode;

        if (item.value === undefined) {
          valueNode = <i>empty</i>;
        } else {
          if ('type' in item) {
            valueNode = <Link href={item.value}>Open</Link>;
          } else if (typeof item.value === 'string') {
            valueNode = item.value.match(/^#[a-f0-9]{3,6}$/i)
              ? <RGB color={item.value}/>
              : item.value;
          } else if (typeof item.value === 'boolean') {
            valueNode = <Checkbox checked={item.value} disabled/>;
          } else {
            valueNode = item.value;
          }
        }

        return (
          <Cell
            className="display-data__line"
            subhead={item.title}
            readOnly
            multiline={true}
            key={idx}
          >
          <span className="display-data__line-value">
            {valueNode}
          </span>
          </Cell>
        );
      })}
    </Section>
  );
}
