// tools/Next.js TS 020/src/components/RGB/RGB.jsx
import './styles.css';

/**
 * @param {string} color
 * @param {string} [className]
 * @param rest
 * @return {import('react').JSX.Element}
 */
export function RGB({ color, className, ...rest }) {
  return (
    <span {...rest} className={['rgb', className].filter(Boolean).join(' ')}>
      <i className="rgb__icon" style={{ backgroundColor: color }}/>
      {color}
    </span>
  );
}

// tools/solidjs-js-tsdk-template-master031/src/components/RGB/RGB.jsx
import { splitProps } from 'solid-js';

import './RGB.css';

/**
 * @typedef {import('solid-js').JSX.IntrinsicElements['span']} RGBProps
 * @property {string} color
 */

/**
 * @param {RGBProps} props
 * @return {import('solid-js').JSXElement}
 */
export function RGB(props) {
  return (
    <span
      {...splitProps(props, ['class'])[0]}
      class={['rgb', props.class].filter(Boolean).join(' ')}
    >
    <i class="rgb__icon" style={{ 'background-color': props.color }}/>
      {props.color}
  </span>
  );
}
